# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'HFIOS' do
pod "Alamofire"
pod "ReactiveCocoa"
end

target 'HFIOSTests' do

end

target 'HFIOSUITests' do

end

